version: '3'
services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql_container
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DIST_PORT}"
    networks:
      - app-net
    env_file:
      - .env
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ..:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - app-net
    depends_on:
      - mysql
    env_file:
      - .env.go.local
networks:
  app-net:
    driver: bridge